name: Auto Deploy to Proxmox VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploying Latest Code
        run: |
          cd /var/www/system-integrator
          git config --global --add safe.directory /var/www/system-integrator
          git fetch origin main
          git reset --hard origin/main

      - name: Reload Containers & Optimize Laravel
        run: |
          cd /var/www/system-integrator
          docker compose up -d --build
          docker compose exec -T app composer install --no-dev --optimize-autoloader
          docker compose exec -T app php artisan migrate --force
          docker compose exec -T app php artisan optimize:clear
          docker compose exec -T app php artisan optimize
          docker compose exec -T app chown -R www-data:www-data storage bootstrap/cache
